# Generated by Django 3.0.6 on 2020-05-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membersprofile',
            name='activity_periods',
        ),
        migrations.AddField(
            model_name='membersprofile',
            name='activity_periods',
            field=models.ManyToManyField(to='assignment_apis.Activity'),
        ),
    ]
